version: '3'
 
services:

  viz:
    image: dockersamples/visualizer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8080:8080"
    deploy:
      restart_policy:
        condition: any
        delay: 5s
      placement:
        constraints: [ node.role == manager ]

  # Менеджер баз данных
  adminer:
    image: adminer
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    ports:
      - 8089:8080
    networks:
      - replica-net
    deploy:
      restart_policy:
        condition: any
        delay: 5s
      placement:
        constraints: [ node.role == manager ]

  # Master БД
  postgres_master:
    image: bitnami/postgresql:15.4.0
    environment:
      POSTGRES_MODE: master
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: docker_replica
      POSTGRES_REPLICATION_USER: sa2
      POSTGRES_REPLICATION_PASSWORD: 1234
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/cities/ru:/etc/cities/ru
    networks:
      - replica-net
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  # Slave БД
  postgres_replica:
    image: bitnami/postgresql:15.4.0
    environment:
      POSTGRES_MODE: slave
      #POSTGRES_USER: sa
      #POSTGRES_PASSWORD: 1234
      #POSTGRES_DB: docker_replica
      #POSTGRES_MASTER_HOST: postgres_master
    links:
      - master:postgres_master
    #volumes:
    #  - postgres-data:/var/lib/postgresql/data
    #networks:
    #  - replica-net
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == worker]
 
volumes:
  postgres-data:

networks:
  replica-net:
    driver: overlay
    name: replica-net
